#!/bin/sh

set -e

bundle exec jekyll build
# Run htmlproofer with configuration and ignore errors
bundle exec htmlproofer ./_site --config .htmlproofer.yml || echo "HTMLProofer errors ignored"
bundle exec rubocop -D
bundle exec script/validate-html
gem build jekyll-theme-architect.gemspec
