name: Jekyll Site CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.147.0
        with:
          ruby-version: 2.7

      - name: Debug environment
        run: |
          echo "Listing current directory:"
          ls -la
          echo "Current working directory:"
          pwd
          echo "Content of the root directory:"
          ls -la ${{ github.workspace }}

      - name: Install dependencies
        run: bundle install

      - name: Build site
        run: bundle exec jekyll build

      - name: Make cibuild executable
        run: chmod +x script/cibuild

      - name: Test site
        run: script/cibuild
